/*****************************************************/
/**  Autogenerated phonestate_cg for cmu_us_vocalid    */
/*****************************************************/
const char * const cmu_us_vocalid_aa_ps[] = { "aa", "aa_1", "aa_2", "aa_3",  0};
const char * const cmu_us_vocalid_ae_ps[] = { "ae", "ae_1", "ae_2", "ae_3",  0};
const char * const cmu_us_vocalid_ah_ps[] = { "ah", "ah_1", "ah_2", "ah_3",  0};
const char * const cmu_us_vocalid_ao_ps[] = { "ao", "ao_1", "ao_2", "ao_3",  0};
const char * const cmu_us_vocalid_aw_ps[] = { "aw", "aw_1", "aw_2", "aw_3",  0};
const char * const cmu_us_vocalid_ax_ps[] = { "ax", "ax_1", "ax_2", "ax_3",  0};
const char * const cmu_us_vocalid_ay_ps[] = { "ay", "ay_1", "ay_2", "ay_3",  0};
const char * const cmu_us_vocalid_b_ps[] = { "b", "b_1", "b_2", "b_3",  0};
const char * const cmu_us_vocalid_ch_ps[] = { "ch", "ch_1", "ch_2", "ch_3",  0};
const char * const cmu_us_vocalid_d_ps[] = { "d", "d_1", "d_2", "d_3",  0};
const char * const cmu_us_vocalid_dh_ps[] = { "dh", "dh_1", "dh_2", "dh_3",  0};
const char * const cmu_us_vocalid_eh_ps[] = { "eh", "eh_1", "eh_2", "eh_3",  0};
const char * const cmu_us_vocalid_er_ps[] = { "er", "er_1", "er_2", "er_3",  0};
const char * const cmu_us_vocalid_ey_ps[] = { "ey", "ey_1", "ey_2", "ey_3",  0};
const char * const cmu_us_vocalid_f_ps[] = { "f", "f_1", "f_2", "f_3",  0};
const char * const cmu_us_vocalid_g_ps[] = { "g", "g_1", "g_2", "g_3",  0};
const char * const cmu_us_vocalid_hh_ps[] = { "hh", "hh_1", "hh_2", "hh_3",  0};
const char * const cmu_us_vocalid_ih_ps[] = { "ih", "ih_1", "ih_2", "ih_3",  0};
const char * const cmu_us_vocalid_iy_ps[] = { "iy", "iy_1", "iy_2", "iy_3",  0};
const char * const cmu_us_vocalid_jh_ps[] = { "jh", "jh_1", "jh_2", "jh_3",  0};
const char * const cmu_us_vocalid_k_ps[] = { "k", "k_1", "k_2", "k_3",  0};
const char * const cmu_us_vocalid_l_ps[] = { "l", "l_1", "l_2", "l_3",  0};
const char * const cmu_us_vocalid_m_ps[] = { "m", "m_1", "m_2", "m_3",  0};
const char * const cmu_us_vocalid_n_ps[] = { "n", "n_1", "n_2", "n_3",  0};
const char * const cmu_us_vocalid_ng_ps[] = { "ng", "ng_1", "ng_2", "ng_3",  0};
const char * const cmu_us_vocalid_ow_ps[] = { "ow", "ow_1", "ow_2", "ow_3",  0};
const char * const cmu_us_vocalid_oy_ps[] = { "oy", "oy_1", "oy_2", "oy_3",  0};
const char * const cmu_us_vocalid_p_ps[] = { "p", "p_1", "p_2", "p_3",  0};
const char * const cmu_us_vocalid_pau_ps[] = { "pau", "pau_1", "pau_2", "pau_3",  0};
const char * const cmu_us_vocalid_r_ps[] = { "r", "r_1", "r_2", "r_3",  0};
const char * const cmu_us_vocalid_s_ps[] = { "s", "s_1", "s_2", "s_3",  0};
const char * const cmu_us_vocalid_sh_ps[] = { "sh", "sh_1", "sh_2", "sh_3",  0};
const char * const cmu_us_vocalid_ssil_ps[] = { "ssil", "pau_5",  0};
const char * const cmu_us_vocalid_t_ps[] = { "t", "t_1", "t_2", "t_3",  0};
const char * const cmu_us_vocalid_th_ps[] = { "th", "th_1", "th_2", "th_3",  0};
const char * const cmu_us_vocalid_uh_ps[] = { "uh", "uh_1", "uh_2", "uh_3",  0};
const char * const cmu_us_vocalid_uw_ps[] = { "uw", "uw_1", "uw_2", "uw_3",  0};
const char * const cmu_us_vocalid_v_ps[] = { "v", "v_1", "v_2", "v_3",  0};
const char * const cmu_us_vocalid_w_ps[] = { "w", "w_1", "w_2", "w_3",  0};
const char * const cmu_us_vocalid_y_ps[] = { "y", "y_1", "y_2", "y_3",  0};
const char * const cmu_us_vocalid_z_ps[] = { "z", "z_1", "z_2", "z_3",  0};
const char * const cmu_us_vocalid_zh_ps[] = { "zh", "zh_1", "zh_2", "zh_3",  0};
const char * const * const cmu_us_vocalid_phone_states[] = {
   cmu_us_vocalid_aa_ps,
   cmu_us_vocalid_ae_ps,
   cmu_us_vocalid_ah_ps,
   cmu_us_vocalid_ao_ps,
   cmu_us_vocalid_aw_ps,
   cmu_us_vocalid_ax_ps,
   cmu_us_vocalid_ay_ps,
   cmu_us_vocalid_b_ps,
   cmu_us_vocalid_ch_ps,
   cmu_us_vocalid_d_ps,
   cmu_us_vocalid_dh_ps,
   cmu_us_vocalid_eh_ps,
   cmu_us_vocalid_er_ps,
   cmu_us_vocalid_ey_ps,
   cmu_us_vocalid_f_ps,
   cmu_us_vocalid_g_ps,
   cmu_us_vocalid_hh_ps,
   cmu_us_vocalid_ih_ps,
   cmu_us_vocalid_iy_ps,
   cmu_us_vocalid_jh_ps,
   cmu_us_vocalid_k_ps,
   cmu_us_vocalid_l_ps,
   cmu_us_vocalid_m_ps,
   cmu_us_vocalid_n_ps,
   cmu_us_vocalid_ng_ps,
   cmu_us_vocalid_ow_ps,
   cmu_us_vocalid_oy_ps,
   cmu_us_vocalid_p_ps,
   cmu_us_vocalid_pau_ps,
   cmu_us_vocalid_r_ps,
   cmu_us_vocalid_s_ps,
   cmu_us_vocalid_sh_ps,
   cmu_us_vocalid_ssil_ps,
   cmu_us_vocalid_t_ps,
   cmu_us_vocalid_th_ps,
   cmu_us_vocalid_uh_ps,
   cmu_us_vocalid_uw_ps,
   cmu_us_vocalid_v_ps,
   cmu_us_vocalid_w_ps,
   cmu_us_vocalid_y_ps,
   cmu_us_vocalid_z_ps,
   cmu_us_vocalid_zh_ps,
   0};
