/*****************************************************/
/**  Autogenerated phonestate_cg for vid_gb_ap    */
/*****************************************************/
const char * const vid_gb_ap_aa_ps[] = { "aa", "aa_1", "aa_2", "aa_3",  0};
const char * const vid_gb_ap_ae_ps[] = { "ae", "ae_1", "ae_2", "ae_3",  0};
const char * const vid_gb_ap_ah_ps[] = { "ah", "ah_1", "ah_2", "ah_3",  0};
const char * const vid_gb_ap_ao_ps[] = { "ao", "ao_1", "ao_2", "ao_3",  0};
const char * const vid_gb_ap_aw_ps[] = { "aw", "aw_1", "aw_2", "aw_3",  0};
const char * const vid_gb_ap_ax_ps[] = { "ax", "ax_1", "ax_2", "ax_3",  0};
const char * const vid_gb_ap_ay_ps[] = { "ay", "ay_1", "ay_2", "ay_3",  0};
const char * const vid_gb_ap_b_ps[] = { "b", "b_1", "b_2", "b_3",  0};
const char * const vid_gb_ap_ch_ps[] = { "ch", "ch_1", "ch_2", "ch_3",  0};
const char * const vid_gb_ap_d_ps[] = { "d", "d_1", "d_2", "d_3",  0};
const char * const vid_gb_ap_dh_ps[] = { "dh", "dh_1", "dh_2", "dh_3",  0};
const char * const vid_gb_ap_eh_ps[] = { "eh", "eh_1", "eh_2", "eh_3",  0};
const char * const vid_gb_ap_er_ps[] = { "er", "er_1", "er_2", "er_3",  0};
const char * const vid_gb_ap_ey_ps[] = { "ey", "ey_1", "ey_2", "ey_3",  0};
const char * const vid_gb_ap_f_ps[] = { "f", "f_1", "f_2", "f_3",  0};
const char * const vid_gb_ap_g_ps[] = { "g", "g_1", "g_2", "g_3",  0};
const char * const vid_gb_ap_hh_ps[] = { "hh", "hh_1", "hh_2", "hh_3",  0};
const char * const vid_gb_ap_ih_ps[] = { "ih", "ih_1", "ih_2", "ih_3",  0};
const char * const vid_gb_ap_iy_ps[] = { "iy", "iy_1", "iy_2", "iy_3",  0};
const char * const vid_gb_ap_jh_ps[] = { "jh", "jh_1", "jh_2", "jh_3",  0};
const char * const vid_gb_ap_k_ps[] = { "k", "k_1", "k_2", "k_3",  0};
const char * const vid_gb_ap_l_ps[] = { "l", "l_1", "l_2", "l_3",  0};
const char * const vid_gb_ap_m_ps[] = { "m", "m_1", "m_2", "m_3",  0};
const char * const vid_gb_ap_n_ps[] = { "n", "n_1", "n_2", "n_3",  0};
const char * const vid_gb_ap_ng_ps[] = { "ng", "ng_1", "ng_2", "ng_3",  0};
const char * const vid_gb_ap_ow_ps[] = { "ow", "ow_1", "ow_2", "ow_3",  0};
const char * const vid_gb_ap_oy_ps[] = { "oy", "oy_1", "oy_2", "oy_3",  0};
const char * const vid_gb_ap_p_ps[] = { "p", "p_1", "p_2", "p_3",  0};
const char * const vid_gb_ap_pau_ps[] = { "pau", "pau_1", "pau_2", "pau_3",  0};
const char * const vid_gb_ap_r_ps[] = { "r", "r_1", "r_2", "r_3",  0};
const char * const vid_gb_ap_s_ps[] = { "s", "s_1", "s_2", "s_3",  0};
const char * const vid_gb_ap_sh_ps[] = { "sh", "sh_1", "sh_2", "sh_3",  0};
const char * const vid_gb_ap_ssil_ps[] = { "ssil", "pau_5",  0};
const char * const vid_gb_ap_t_ps[] = { "t", "t_1", "t_2", "t_3",  0};
const char * const vid_gb_ap_th_ps[] = { "th", "th_1", "th_2", "th_3",  0};
const char * const vid_gb_ap_uh_ps[] = { "uh", "uh_1", "uh_2", "uh_3",  0};
const char * const vid_gb_ap_uw_ps[] = { "uw", "uw_1", "uw_2", "uw_3",  0};
const char * const vid_gb_ap_v_ps[] = { "v", "v_1", "v_2", "v_3",  0};
const char * const vid_gb_ap_w_ps[] = { "w", "w_1", "w_2", "w_3",  0};
const char * const vid_gb_ap_y_ps[] = { "y", "y_1", "y_2", "y_3",  0};
const char * const vid_gb_ap_z_ps[] = { "z", "z_1", "z_2", "z_3",  0};
const char * const vid_gb_ap_zh_ps[] = { "zh", "zh_1", "zh_2", "zh_3",  0};
const char * const * const vid_gb_ap_phone_states[] = {
   vid_gb_ap_aa_ps,
   vid_gb_ap_ae_ps,
   vid_gb_ap_ah_ps,
   vid_gb_ap_ao_ps,
   vid_gb_ap_aw_ps,
   vid_gb_ap_ax_ps,
   vid_gb_ap_ay_ps,
   vid_gb_ap_b_ps,
   vid_gb_ap_ch_ps,
   vid_gb_ap_d_ps,
   vid_gb_ap_dh_ps,
   vid_gb_ap_eh_ps,
   vid_gb_ap_er_ps,
   vid_gb_ap_ey_ps,
   vid_gb_ap_f_ps,
   vid_gb_ap_g_ps,
   vid_gb_ap_hh_ps,
   vid_gb_ap_ih_ps,
   vid_gb_ap_iy_ps,
   vid_gb_ap_jh_ps,
   vid_gb_ap_k_ps,
   vid_gb_ap_l_ps,
   vid_gb_ap_m_ps,
   vid_gb_ap_n_ps,
   vid_gb_ap_ng_ps,
   vid_gb_ap_ow_ps,
   vid_gb_ap_oy_ps,
   vid_gb_ap_p_ps,
   vid_gb_ap_pau_ps,
   vid_gb_ap_r_ps,
   vid_gb_ap_s_ps,
   vid_gb_ap_sh_ps,
   vid_gb_ap_ssil_ps,
   vid_gb_ap_t_ps,
   vid_gb_ap_th_ps,
   vid_gb_ap_uh_ps,
   vid_gb_ap_uw_ps,
   vid_gb_ap_v_ps,
   vid_gb_ap_w_ps,
   vid_gb_ap_y_ps,
   vid_gb_ap_z_ps,
   vid_gb_ap_zh_ps,
   0};
