/*******************************************************/
/**  Autogenerated lts rules (regex) for cmu     */
/**  from wfst/    */
/*******************************************************/

#include "cst_string.h"
#include "cst_lts.h"
#include "cst_lexicon.h"

const char * const cmu_lts_phone_table[75] = 
{
    "epsilon",
    "eh1",
    "aa1",
    "aa0",
    "aw1",
    "ax0",
    "ao1",
    "ey1",
    "ey0",
    "ao0",
    "ih1",
    "ay0",
    "ae1",
    "aw0",
    "ow0",
    "ow1",
    "ae0",
    "ih0",
    "ah1",
    "eh0",
    "w-ey1",
    "y-ax0",
    "ay1",
    "ah0",
    "b",
    "ch",
    "k",
    "s",
    "t-s",
    "sh",
    "t",
    "d",
    "jh",
    "iy1",
    "iy0",
    "uw1",
    "y-uw1",
    "oy1",
    "uw0",
    "y-uw0",
    "oy0",
    "f",
    "g",
    "zh",
    "hh",
    "y",
    "l",
    "ax0-l",
    "m",
    "ax0-m",
    "m-ae1",
    "m-ax0",
    "ng",
    "n",
    "n-y",
    "uh1",
    "uh0",
    "w",
    "w-ah1",
    "er1",
    "p",
    "er0",
    "r",
    "z",
    "th",
    "dh",
    "y-er0",
    "y-uh1",
    "y-er1",
    "v",
    "k-s",
    "g-zh",
    "k-sh",
    "g-z",
    NULL
};

const char * const cmu_lts_letter_table[30] = 
{
    "nothing",
    "#",
    "0",
    "a",
    "b",
    "c",
    "d",
    "e",
    "f",
    "g",
    "h",
    "i",
    "j",
    "k",
    "l",
    "m",
    "n",
    "o",
    "p",
    "q",
    "r",
    "s",
    "t",
    "u",
    "v",
    "w",
    "x",
    "y",
    "z",
    NULL
};

const cst_lts_addr cmu_lts_letter_index[27] = 
{
    0, /* a */
    5944, /* b */
    6021, /* c */
    6710, /* d */
    6913, /* e */
    11619, /* f */
    11830, /* g */
    12390, /* h */
    12648, /* i */
    16914, /* j */
    17033, /* k */
    17052, /* l */
    17609, /* m */
    17671, /* n */
    17873, /* o */
    22000, /* p */
    22034, /* q */
    22035, /* r */
    23931, /* s */
    24899, /* t */
    25343, /* u */
    27220, /* v */
    27231, /* w */
    27406, /* x */
    27453, /* y */
    27989, /* z */
    0
};

