/*******************************************************/
/**  Autogenerated lts rules (regex) for cmu     */
/**  from wfst/    */
/*******************************************************/

#include "cst_string.h"
#include "cst_lts.h"
#include "cst_lexicon.h"

const char * const cmu_lts_phone_table[76] = 
{
    "epsilon",
    "eh1",
    "aa1",
    "ey1",
    "aw1",
    "ax0",
    "ao1",
    "ay0",
    "aa0",
    "ey0",
    "ae1",
    "ih1",
    "aw0",
    "ow0",
    "ao0",
    "ow1",
    "eh0",
    "ih0",
    "w-ax0",
    "w-ey1",
    "y-ax0",
    "ae0",
    "ay1",
    "ah0",
    "ah1",
    "b",
    "ch",
    "k",
    "s",
    "t-s",
    "sh",
    "d",
    "t",
    "jh",
    "iy1",
    "iy0",
    "uw1",
    "y-uw1",
    "oy1",
    "y-uw0",
    "uw0",
    "oy0",
    "f",
    "g",
    "zh",
    "hh",
    "y",
    "l",
    "ax0-l",
    "m",
    "ax0-m",
    "m-ae1",
    "m-ax0",
    "ng",
    "n",
    "n-y",
    "uh1",
    "uh0",
    "w",
    "w-ah1",
    "er1",
    "p",
    "r",
    "er0",
    "z",
    "th",
    "dh",
    "y-er0",
    "y-uh1",
    "y-er1",
    "v",
    "k-s",
    "g-zh",
    "k-sh",
    "g-z",
    NULL
};

const char * const cmu_lts_letter_table[30] = 
{
    "nothing",
    "#",
    "0",
    "a",
    "b",
    "c",
    "d",
    "e",
    "f",
    "g",
    "h",
    "i",
    "j",
    "k",
    "l",
    "m",
    "n",
    "o",
    "p",
    "q",
    "r",
    "s",
    "t",
    "u",
    "v",
    "w",
    "x",
    "y",
    "z",
    NULL
};

const cst_lts_addr cmu_lts_letter_index[27] = 
{
    0, /* a */
    5317, /* b */
    5365, /* c */
    6038, /* d */
    6155, /* e */
    10522, /* f */
    10667, /* g */
    11177, /* h */
    11409, /* i */
    15253, /* j */
    15373, /* k */
    15388, /* l */
    15725, /* m */
    15767, /* n */
    16121, /* o */
    19698, /* p */
    19736, /* q */
    19737, /* r */
    21750, /* s */
    22781, /* t */
    23081, /* u */
    24822, /* v */
    24830, /* w */
    24992, /* x */
    25037, /* y */
    25493, /* z */
    0
};

